name: RS-mini-projekt-Paolo-Bursic
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-doc=0.0.4=py313h06a4308_0
  - annotated-types=0.6.0=py313h06a4308_1
  - anyio=4.10.0=py313h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - fastapi=0.121.1=py313hd0c6730_0
  - idna=3.11=py313h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pydantic=2.12.4=py313h06a4308_0
  - pydantic-core=2.41.5=py313h498d7c9_1
  - python=3.13.9=h7e8bc2b_100_cp313
  - python_abi=3.13=1_cp313
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py313h06a4308_0
  - sniffio=1.3.0=py313h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - starlette=0.47.3=py313h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.2=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - click==8.3.1
      - h11==0.16.0
      - httptools==0.7.1
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: /home/paolo/miniconda3/envs/RS-mini-projekt-Paolo-Bursic
